JuliaDiff/FiniteDifferences.jl

.travis.yml, Project.toml, REQUIRE, appveyor.yml, docs/Project.toml, docs/make.jl
Summary of changes:
* Add a Project.toml file for the package
* Deploy documentation on Julia 1.0 using a doc-specific Project.toml
* Test on Julia 0.7 and 1.0 on both Travis and AppVeyor, and modernize their setup
* Remove stdlib packages from REQUIRE (messes with METADATA)
=> Updates for Julia 1.0

Manifest.toml, Project.toml, src/grad.jl, test/grad.jl
`similar` is only guaranteed to do sensible things for `Arrays`, as opposed to any arbitrary `AbstractArray`. Consequently, I propose constrained the types of the arrays involved in `gradient` / `jacobian` / `jvp` / `j′vp` to reflect this.
This problem actually caught me out when working with `BlockArrays`. `similar(block_vector)` produces a `BlockVector` whose indices are undefined because the memory for the data isn't allocated, which caused some undefined reference issues.
@wesselb @ararslan what are your thoughts on this?
=> Proposal: Tighten types

src/grad.jl, test/grad.jl
Relates to [this PR](https://github.com/JuliaDiff/ChainRules.jl/pull/14). Makes it easier to compute jacobian-vector product and jacobian-transpose-vector products.
=> Implements extensions to jvp and adjoint

README.md
Also remove the PkgEval badges for 0.6 and 0.7, as they're no longer updated.
=> Correct link to AppVeyor build

src/grad.jl, test/grad.jl
Currently `to_vec` fails for inputs wrapped in these types, so this adds a method that handles them.
=> Add to_vec for Adjoint and Transpose

src/methods.jl, test/methods.jl
This introduces a type-based approach that works slightly differently than the current API. Upon construction of a `FDMethod` subtype, the order of the method and the order of the derivative are checked for agreement, and the grid and coefficients are computed and stored. Instances of the types are callable, and doing so produces the value of the derivative. It works recursively when adaptively computing the bound, which results in a better step size and thus a (hopefully) more robust estimate of the derivative.
"Why types?" you may be asking. It just seemed like an efficient way of expressing things and storing intermediate values.
"Where did this adaptive thing come from?" From none other than Wessel himself: https://github.com/wesselb/fdm.
=> Add adaptive function bound computation

src/grad.jl, test/grad.jl
Supercedes #14 . Fixes a bug in which the length of the vectorised object should be used, rather than the length of the original object, when these lengths are not equal.
=> Fix issue with tuples

Project.toml
Required to register the v0.6.1 tag. @wesselb, we should probably delete the existing v0.6.1 tag then after this is merged, use Registrator and TagBot to have the tag done automatically.
=> Set version to 0.6.1

src/grad.jl, test/grad.jl
Adds support for `Dict`s by way of adding support for `Vector`s of arbitrary things. In particular, the primitive is a `Vector{<:Real}`, while a `Vector` containing anything else will have `to_vec` called recursively on its elements.
This makes it straightforward to then implement `Dict` by transforming it into a `Vector`, and then back to a `Dict`.
=> Dicts, Vectors, and Arrays

src/methods.jl, test/methods.jl
=> Check that the derivative is nonnegative, and handle the case `q == 0`

Project.toml
- We intend to register FiniteDifferences.jl as a new package, so we need a new UUID.
- Because renaming the package from FDM -> FiniteDifferences is hard/confusing/undefined behaviour, as far as anyone understands
- Note we'll just continue with the version numbers from FDM, so the next release (registering the package) will have version `0.7`
=> Use a new UUID for registering as a new package

src/grad.jl
We should never have been using the `jacobian` function to estimate jacobian-vector products. Instead, one should estimate the jvp directly by estimating the derivative in the direction of `ẋ`. It's definitely faster, and probably more numerically stable.
=> Faster jvp-s

src/grad.jl, test/grad.jl
This is needed for tests in JuliaDiff/ChainRules.jl#95.
=> Relax type constraints to allow complex jvp

Project.toml, src/grad.jl, test/grad.jl
I didn't notice this yesterday until I start working on the Zygote PR today. So the basically current return value type of single variable grad/jacobian is not very consistent with multivariate grad/jacobian. It should return `(x, )`, this is causing extra handling when I implement `gradcheck` using the jacobians in Zygote.
=> change return type of grad/jacobian to match args

src/grad.jl
We can avoid copying every element every step if we just mutate the element we want to mutate on the original matrix, then mutate it back again after so we still have the original for the next step.
My micro benchmarks show this helps a bit.
=> Do gradient via mutating and unmutating cell

Project.toml, src/FiniteDifferences.jl, src/grad.jl, src/to_vec.jl, test/grad.jl, test/runtests.jl, test/to_vec.jl
This is a fairly substantial PR, motivated in no small part by @Roger-luo 's work in #54 .
In particular it
1. completely refactors `jacobian` for performance reasons. Our previous implementation was really quite bad (my fault) -- it required ~~O(input_dims^2)~~ O(input_dims * output_dims) function evaluations rather than O(input_dims).
2. refactors `grad` to utilise `jpvp`. `grad` is now a single-line function that utilises the new `jacobian` implementation. This is a substantial drop in code complexity with no loss of functionality, as much of the code that we had before to handle dictionaries etc is completely gone. The result is that `grad` now depends on `to_vec` like everything else in this package.
3. the new implementation of `jacobian` has the pleasing advantage of doing away …
=> Refactor jacobian and grad

Project.toml, src/methods.jl, test/methods.jl
Fixed #64 
Turns out this can make a difference.
This not only gets result on julia 1.4 up to the standard of julia 1.2,
but actually does much more than that, significantly improving out accuracy
```julia
julia> using FiniteDifferences
julia> k3 = FiniteDifferences.fdm(FiniteDifferences.central_fdm(9, 5), y->exp(y), 1.0, adapt=4)
2.7182817496168528
julia> abs(k3-exp(1))  # Should be 0
7.884219233034173e-8
julia> f(x) = @. 4x^3 + 3x^2 + 2x + 1
f (generic function with 1 method)
julia> FiniteDifferences.fdm(FiniteDifferences.central_fdm(9, 3), f, 1.0, adapt=4) - 24
5.538680625249981e-12
```
```julia
julia> using FiniteDifferences
julia> k3 = FiniteDifferences.fdm(FiniteDifferences.central_fdm(9, 5), y->exp(y), 1.0, adapt=4)
2.7182663156747684
julia> abs(k3-exp(1))  # Should be 0 …
```
=> Compute coeffs using Rationals

Project.toml, src/to_vec.jl, test/to_vec.jl
As it turns out I was over-zealous with the type checking. Currently if you provide an `Int` input when computing differences, `to_vec` will make it a float if needs be. While it's debatable whether or not this is desirable behaviour, it's clearly breaking if it changes.
The changes to `adjoint` / `transpose` were just wrong, and they've now been reverted and a test added.
@oxinabox I would appreciate it greatly if you could verify whether these changes make all of the `ChainRules` tests pass on your machine. For some reason, but machine is throwing very strange errors in places where CI doesn't have them. I'm not sure whether it's an issue with my Julia install, my computer is dying (it could very well be, it's old and has been behaving a little strangely recently), something else that's …
=> Revert some of 0.9.4

Project.toml, src/methods.jl
Closes #72.
Now we are faster than we were even on 0.9.2 before I made it slow.
This does part of #61 in particular part of this comment
https://github.com/JuliaDiff/FiniteDifferences.jl/pull/61#issuecomment-605456372
Looks like the cause was #65.
Am going to build a fix shortly
First two timings are as per https://github.com/JuliaDiff/FiniteDifferences.jl/issues/72#issuecomment-614141608
44.084013 seconds (80.42 M allocations: 4.397 GiB, 3.80% gc time)
29.377420 seconds (28.23 M allocations: 1.830 GiB, 1.86% gc time)
27.364521 seconds (28.23 M allocations: 1.830 GiB, 1.76% gc time)
27.871987 seconds (28.23 M allocations: 1.830 GiB, 1.79% gc time)
18.984412 seconds (61.60 M allocations: 3.236 GiB, 6.57% gc time)
1.072190 seconds (10.23 M allocations: 737.725 MiB, 10.14% gc time)
1.090849 …
=> Memoize Coeffs

Project.toml, src/grad.jl, src/to_vec.jl, test/grad.jl, test/to_vec.jl
Addresses #75 .
This is a first attempt, and it's not clear to be whether this is precisely the correct API for this -- we treat complex numbers as a 2-vector of reals. This lets us re-cycle the `to_vec` interface and avoid having to modify any of the code that actually does differencing.
@sethaxen does this address your use case? Maybe take a look at the extra tests to get a flavour of the kind of results you could expect to see.
=> Fixes handling of complex numbers

Project.toml, src/to_vec.jl, test/to_vec.jl
The `to_vec` function for `Hermitian` uses the same approach as used in #85.
=> Reconstruct Symmetric using uplo, and generalize for Hermitian also

Project.toml, src/grad.jl, test/grad.jl
This PR fixes #93. For all multi-arg functions, `jvp` only returned the tangent of the first output (for vector output, returned the first scalar; for tuple output, returned the first entry of the tuple).
=> Return correct tangent for multi-arg functions

Project.toml, src/grad.jl, test/grad.jl
The Jacobian for a function with an empty primal will be `Any[]` regardless of the function, which can't be multiplied by the cotangent on the output. This PR fixes #92 by detecting an empty primal and returning an empty cotangent with the same eltype as that of the cotangent of the output.
=> Return empty cotangent for empty primal

Project.toml, docs/src/pages/api.md, src/methods.jl, test/methods.jl, test/runtests.jl
As discussed with @wesselb in #98 .
Wessel: I'm getting test failures with second-order methods and `Float32`s caused by a loss in accuracy. Any chance that you could take a look to see whether the accuracy is as expected, or whether there's something going on?
=> add_tiny + tests

docs/Manifest.toml, docs/Project.toml
This does not solve #101 , no logic around how that is done has changed AFAIK.
But it does give us the option to increase the timeout, if that is what we think needs to be done.
Also it adds pretty slick dark mode
=> update documenter version

Project.toml, src/methods.jl, test/methods.jl
This came up in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/138
There's some functionality that we've got that returns a `Bool`. `add_tiny` doesn't like this, so this is a fix for that.
=> Tweak add_tiny

docs/make.jl
Documenter marks linkcheck as experimental, and has it disabled by default.
Given removing it will just fix #101  and let us stop wasting time on it, not using an experimental feature seems like a good idea.
https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.makedocs
> **Experimental keywords**
> 
> In addition to standard arguments there is a set of non-finalized experimental keyword arguments. The behaviour of these may change or they may be removed without deprecation when a minor version changes (i.e. except in patch releases).
> 
> linkcheck – if set to true makedocs uses curl to check the status codes of external-pointing links, to make sure that they are up-to-date. The links and their status codes are printed to the standard output. If strict is also enabled …
=> Stop using linkcheck.

Project.toml, src/to_vec.jl, test/to_vec.jl
Does what it says in the title.
@mcabbott would appreciate knowing if this solves your problem and your review if you've got the time.
=> Implement to_vec for PermutedDimsArray

Project.toml, README.md, docs/Manifest.toml, docs/src/pages/api.md, src/FiniteDifferences.jl, src/methods.jl, test/grad.jl, test/methods.jl
This PR simplifies the internals, which have become a little convoluted over time. Also adds `extrapolate_fdm` (#107).
Important changes:
- There is only one type `FiniteDifferenceMethod`, which implements an FDM on an arbitrary grid.
- There is no function `fdm` anymore. All estimates are executed by calling the FDM directly.
- Some keyword arguments have changed place.
TODO:
=> WIP: Rework and Simplify Internals

Project.toml, src/to_vec.jl, test/to_vec.jl
We already had ChainRulesCore as a dependency.
ChainRulesTestUtils was type-piratically defining `to_vec` on `Composite{<:Tuple, <:Tuple}`
This PR adds for `AbstractZero` (useful if working with a deep structure containing some Zero parts).
and it adds for `Composite` on structs.
Supporting to_vec on Composites of structs will close the last parts of
https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/24
which really should have been on this repo.
I don't think it alone is enough to do finite differencing on structs, but it is a first step.
This works without https://github.com/JuliaDiff/ChainRulesCore.jl/pull/230
but for the tests to pass it needs that, since equality was defined wong
=> Defined to_vec for ChainRulesCore differential types

Project.toml, src/to_vec.jl
`to_vec` for `AbstractZero`s was returning a non-empty vector, which is both unnecessary and potentially incorrect (`AbstractZero`s are structural, so if `FiniteDifferences` were to perturb an `AbstractZero`, bad things would presumably happen).
=> Tweak Zero to vec

.github/workflows/CI.yml, .github/workflows/Documenter.yml, .github/workflows/JuliNightly.yml, .github/workflows/Nightly.yml, README.md
Basically the same as https://github.com/JuliaDiff/ChainRules.jl/pull/309, but with Documenter.
=> Run CI and deploy docs with GitHub Actions

Project.toml, src/to_vec.jl, test/to_vec.jl
Fixes #117 as well as an issue with `to_vec(::Tuple)` being type-unstable.
=> Add tests and fixes for to_vec type-stability

Project.toml, src/methods.jl, test/methods.jl
The function `add_tiny` was a bit of a hack to deal with zeros. The new addition `estimate_magnitude` deals with this in a better way, at the cost of more function evaluations.
This should address #124:
```julia
julia> (p -> FiniteDifferences.central_fdm(p, 1)(cosc, 0)).(2:10) .+ (pi ^ 2) / 3
9-element Array{Float64,1}:
-2.487109898532124
-3.1522345644852123e-6
-4.327381120106111e-9
-8.283298491562618e-10
1.3939516207983615e-11
3.93636234718997e-11
9.558132063602898e-12
-2.1227464230832993e-13
1.213251721310371e-12
```
The package can be pushed to estimate at high accuracies:
```julia
julia> FiniteDifferences.central_fdm(10, 1, adapt=3)(cosc, 0) + (pi ^ 2) / 3
-3.019806626980426e-14
```
This PR also adds a test that checks that above two cases.
=> WIP: Remove `add_tiny` and add `estimate_magitude`

Project.toml, src/to_vec.jl, test/to_vec.jl
At present, `to_vec(randn(5)')[2](randn(5))` produces an `Adjoint` whose `parent` is a `Matrix`, rather than a `Vector`. While this doesn't generally seem to be too problematic, it recently caused me an issue with some AD testing code. Regardless, it doesn't feel like the natural thing to do.
This patch changes this behaviour to produce an `Adjoint` whose `parent` is a `Vector`. Same for `Transpose`.
=> Small fix for to_vec(::Adjoint) and to_vec(::Transpose)

Project.toml, src/to_vec.jl, test/to_vec.jl
As @sethaxen pointed out in #133, #131 accidentally disabled a number of tests, and introduced a weird bug. This PR currently resolves the first of these problems, and I'm presently working on the second.
=> WIP: Adjoint problems

.github/workflows/IntegrationTestChainRules.yml
As proposed in https://github.com/JuliaDiff/FiniteDifferences.jl/issues/132#issuecomment-757393572, this PR adds an integration test workflow for ChainRules (copied from the equivalent workflow used by ChainRulesCore). ChainRules extensively uses FiniteDifferences, and sometimes regressions here are not caught by our test suite but do cause ChainRules failures. This should help us catch these.
=> Add ChainRules integration test

README.md
=> Add ToC to README for better navigability

Project.toml, src/to_vec.jl, test/to_vec.jl
Currently the user has to define a `to_vec` function for every new struct. This PR adds a fallback for structs.
Thanks @willtebbutt for the implementation, I've just added a line to check against structs with no fieldnames (`String`s and singleton types for example). I couldn't think of anything else messing this up, but I'll have another think about it on Monday.
=> Fallback `to_vec` intended for structs

.github/workflows/CI.yml
This adds the nightly build notifications, so an RSE at invenia will be notified if anything breaks.
=> Notifications from Nightly Build to Invenia slack

Project.toml
I've added the constraint to 1 since it wouldn't automerge: https://github.com/JuliaRegistries/General/pull/30252 (the GitHub actions comment was edited)
I've tested locally that 0.12 also passes tests
=> Relax compatibility with StaticArrays

test/to_vec.jl
It looks like there are some type inference issues with `reduce` in 1.6
https://github.com/JuliaLang/julia/issues
So removing these checks for now to make CI work again
=> Fix 1.6 CI

Project.toml, src/to_vec.jl, test/to_vec.jl
I've looked into whether we can simply constrain the `to_vec` generic `AbstractVector/Array` to `Strided`, and it almost works.
It's just these `ChainRules` tests which need the `SubArray` in the `Union` (I didn't investigate why the `SubArray`s inside the `Strided` `Union` do not contain this case):
https://github.com/JuliaDiff/ChainRules.jl/blob/38caf4bfdb8af616fcbe7626d10699608af21904/test/rulesets/Base/arraymath.jl#L36-L42 
@willtebbutt this seems to solve a lot of issues that we were seeing (https://github.com/JuliaDiff/FiniteDifferences.jl/issues/149, https://github.com/JuliaDiff/FiniteDifferences.jl/issues/141).
Is there a reason we haven't changed this before? I guess partly because it is breaking, but are there any bad things that can happen if we go ahead with this? It seems …
=> Constrain type in `to_vec(::AbstractArray/Vector)`

test/to_vec.jl
`reduce` has [broken type inference on 1.6.0](https://github.com/JuliaLang/julia/issues/40277). This has been fixed in 1.6.1.
=> unbroken type inference

Project.toml, src/rand_tangent.jl, test/rand_tangent.jl
Closes https://github.com/JuliaDiff/FiniteDifferences.jl/issues/149
This is my preferred alternative to  https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/142#issuecomment-829287623
Note that it is **not** the case that if all my fields do not exist then i do not exist,
but it is the case that if all my fields are not perturbable then I am not pertablable.
Which is what `DoesNotExist` actually means, and we should rename it.
=> make rand_tangent of struct with no perturbable fields return DoesNotExist

Project.toml, src/difference.jl, src/rand_tangent.jl, test/difference.jl, test/rand_tangent.jl
closes https://github.com/JuliaDiff/FiniteDifferences.jl/issues/151
=> Make rand_tangent on adjoint an transpose return natural

Project.toml, src/rand_tangent.jl, test/rand_tangent.jl
I don't think we ever cared about rand_tangent giving actual random valuis.
This rigs it so they are ones with fairly short decimal expressions.
(vs the standard for a Float of 19 charater and 42 characters for a Complex).
It is a bit of a balencing act between restricting the sample space, and getting things that are short.
I have 2 stratergies:
1. `round(k*randn(x) sigdigits=n, base=2)` this is I guess pretty general, but it resticts the space to `z*2^-n`.
2. `rand(range)` there are certain ranges of values that floating point can exactly represent. For example all Float's in  `Base` can exactly represent `-9:0.001:9` (but not `-9:0.0001:9`).
I use stratergy 2 for `Float64` and `ComplexF64` (the types we care about the most)
and strategy 1 for everything else.
Though perhaps I should …
=> make rand_tangent give only nice numbers

test/runtests.jl
Should close #169 
the problem is printing of BigFloats only mostly works right using out method.
I am pretty sure this is a bug in julia / MPFR
So we can set the seed to stop ourselves from getting unlucky
=> Fix the random seed during testing

Project.toml, src/rand_tangent.jl, test/rand_tangent.jl
So far
```julia
julia> ChainRulesTestUtils.rand_tangent(Float64)
ERROR: StackOverflowError:
Stacktrace:
[1] rand_tangent(rng::Random._GLOBAL_RNG, x::Module)
@ FiniteDifferences ~/JuliaEnvs/ChainRulesTestUtils.jl/dev/FiniteDifferences/src/rand_tangent.jl:50
[2] (::FiniteDifferences.var"#3#5"{Random._GLOBAL_RNG, Core.TypeName})(field_name::Symbol)
@ FiniteDifferences ~/JuliaEnvs/ChainRulesTestUtils.jl/dev/FiniteDifferences/src/rand_tangent.jl:51
[3] map (repeats 2 times)
@ ./tuple.jl:216 [inlined]
[4] rand_tangent(rng::Random._GLOBAL_RNG, x::Core.TypeName)
@ FiniteDifferences ~/JuliaEnvs/ChainRulesTestUtils.jl/dev/FiniteDifferences/src/rand_tangent.jl:50
[5] (::FiniteDifferences.var"#3#5"{Random._GLOBAL_RNG, DataType})(field_name::Symbol)
@ FiniteDifferences …
```
=> Add `rand_tangent` for types

.github/workflows/Documenter.yml, Project.toml, docs/Manifest.toml, src/to_vec.jl, test/to_vec.jl
Needed for https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/159.
=> Add `to_vec(::Thunk)`

Project.toml, src/rand_tangent.jl, test/rand_tangent.jl
Fixes #179 
Minor bugfix. Address edge case where `rand_tangent` is called with zero-arrays - i.e. `fill(1.0)` to maintain shape.
=> Rand tangent zero-dimensional arrays

Project.toml, src/to_vec.jl, test/to_vec.jl
Before we would see something like:
```julia
julia> cca = CustomConstructorArray(rand(2, 3));
julia> v, b = to_vec(cca); b(v)
T = CustomConstructorArray{Float64, 2, Matrix{Float64}}
ERROR: MethodError: no method matching CustomConstructorArray{Float64, 2, Matrix{Float64}}(::Matrix{Float64})
Stacktrace:
[1] (::FiniteDifferences.var"#structtype_from_vec#27"{CustomConstructorArray{Float64, 2, Matrix{Float64}}, FiniteDifferences.var"#Tuple_from_vec#43"{Tuple{Int64}, Tuple{Int64}, Tuple{typeof(identity)}}, Tuple{FiniteDifferences.var"#Array_from_vec#32"{Matrix{Float64}, typeof(identity)}}})(v::Vector{Float64})
@ FiniteDifferences ~/JuliaEnvs/test/alex/dev/FiniteDifferences/src/to_vec.jl:39
[2] top-level scope
@ REPL[13]:1
```
because there is a custom constructor. Not the best solution (one …
=> try to handle structs with custom constructors

Project.toml, src/FiniteDifferences.jl, src/deprecated.jl, test/deprecated.jl, test/runtests.jl
Partner to https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/189
=> deprecate rand_tangent

src/to_vec.jl, test/to_vec.jl
Fixes #114 and should help cleaning the tests in https://github.com/JuliaDiff/ChainRules.jl/pull/306.
=> Implement to_vec for matrix factorizations

Project.toml, src/to_vec.jl, test/to_vec.jl
I am surprised we didn't run into this earlier.
```julia
julia> v, b = to_vec(Float64)
ERROR: StackOverflowError:
Stacktrace:
[1] fieldnames
@ ./reflection.jl:177 [inlined]
[2] to_vec(x::Type{Float64})
@ FiniteDifferences ~/JuliaEnvs/test/alex/dev/FiniteDifferences/src/to_vec.jl:42
[3] (::FiniteDifferences.var"#206#209"{Core.TypeName})(name::Symbol)
@ FiniteDifferences ~/JuliaEnvs/test/alex/dev/FiniteDifferences/src/to_vec.jl:38
[4] map (repeats 4 times)
@ ./tuple.jl:216 [inlined]
[5] to_vec(x::Core.TypeName)
@ FiniteDifferences ~/JuliaEnvs/test/alex/dev/FiniteDifferences/src/to_vec.jl:54
[6] (::FiniteDifferences.var"#206#209"{DataType})(name::Symbol)
@ FiniteDifferences ~/JuliaEnvs/test/alex/dev/FiniteDifferences/src/to_vec.jl:38
[7] map(f::FiniteDifferences.var"#206#209"{DataType}, …
```
=> Implement `to_vec` for `DataType`s

.github/workflows/CI.yml
See https://github.com/JuliaDiff/ChainRulesCore.jl/pull/519
though i think docs might also not be working as we don't have the devbranch set?
and are using a very old version of Documentor?
but that is another PR
=> Run CI on pushes to main

Project.toml, src/to_vec.jl, test/to_vec.jl
=> Add `to_vec(CartesianIndex)`

Project.toml, src/FiniteDifferences.jl, src/to_vec.jl, test/runtests.jl, test/to_vec.jl
Needed for testing https://github.com/JuliaDiff/ChainRules.jl/pull/586
=> implement `to_vec` for sparse arrays

Project.toml, src/methods.jl
Fixes the warning
```julia
WARNING: method definition for #extrapolate_fdm#17 at /home/david/.julia/packages/FiniteDifferences/VpgIT/src/methods.jl:577 declares type variable T but does not use it.
```
that shows up when loading FiniteDifferences with Julia 1.8.
=> Remove unused type parameter

Project.toml, test/to_vec.jl
The comparison involves elementwise `getindex` anyway, so it should be faster to first compute the matrix and then compare. Also, this will stop working after https://github.com/JuliaLang/julia/pull/46196 is merged.
=> Matrixify Q's in tests

src/to_vec.jl, test/to_vec.jl
On the main branch, `to_vec(t::Tuple{})` fails as it attempts to call `cumsum` on an empty vector of type `Union{}` (obtained by collecting the empty tuple). It is a bit of a corner case, but it can cause `test_rrule` to fail when the output has an empty tuple or named tuple.
This PR specialcases empty tuples to fix that.
On main:
```julia
julia> using FiniteDifferences
julia> v, reconstruct = FiniteDifferences.to_vec(())
ERROR: MethodError: Base.ArithmeticStyle(::Type{Union{}}) is ambiguous.
```
With this PR:
```julia
julia> using FiniteDifferences
[ Info: Precompiling FiniteDifferences [26cc04aa-876d-5657-8c51-4c34ba976000]
julia> v, reconstruct = FiniteDifferences.to_vec(())
(Bool[], FiniteDifferences.var"#Tuple_from_vec#51"())
julia> reconstruct(v)
()
```
=> support empty tuples and named tuples

src/methods.jl, test/methods.jl
=> Do not require that function arguments are ::Function.

Project.toml, src/to_vec.jl, test/to_vec.jl
Encountered in https://github.com/JuliaDiff/ChainRules.jl/pull/758
Problem was there is a `du2` field which isn't used except as an implementation detail of `lu`.
It is the value on the diag(x, 2)` but its not used by `==` etc because it's not part of the actual tridiagonal.
Reading this was causing errors with reading undefined values.
=> Support Tridiagonal in to_vec
